### ISSUE TITLE
Include instructions / a readme

### ISSUE THREAD

**Issue by Lucas-vdr-Horst** [JBierenbroodspot/PROJA#1]
Could you include a `README.md` with instructions on how to install and run the project?

For installation a `requirements.txt` or `setup.py` would be very nice,  
also saw you've done something with environment variables, instructions on that would be nice too.

**Comment by JBierenbroodspot** [comment]
I have added a `README.md` and `requirements.txt`. Please let me know if this helps.

**Comment by Lucas-vdr-Horst** [comment]
Yeah, looks good👍
